Added German translations
bisand/net.biseth.myenergi pull request #15
Opened 2022-01-02 18:11 UTC by Spijkmans

Hi @bisand  I made the German translations. Would you please review these?

2022-01-02 20:11 UTC, bisand requested changes
Thanks! The translations look OK to me, but for some reason an extra **.homeycompose** folder has added under the original .homeycompose folder ( .homeycompose/.homeycompose/ ).
Please remove that folder, and also add **.DS_Store** to .gitignore and try to update the PR.

2022-01-02 22:38 UTC, Spijkmans commented
Ok I removed the extra files and directory, first time I did it on my Mac...
Let's say we keep on learning ;)

2022-01-03 05:14 UTC, bisand approved these changes

2022-01-03 05:15 UTC, bisand commented
Perfect! Thanks!

2022-01-03 05:16 UTC, merged